# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/nickk/Documents/Lab1LP/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/nickk/Documents/Lab1LP/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/nickk/Documents/Lab1LP/build/CMakeFiles /mnt/c/Users/nickk/Documents/Lab1LP/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/nickk/Documents/Lab1LP/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GEOMETRIA

# Build rule for target.
GEOMETRIA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GEOMETRIA
.PHONY : GEOMETRIA

# fast build rule for target.
GEOMETRIA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/build
.PHONY : GEOMETRIA/fast

circulo.o: circulo.cpp.o
.PHONY : circulo.o

# target to build an object file
circulo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/circulo.cpp.o
.PHONY : circulo.cpp.o

circulo.i: circulo.cpp.i
.PHONY : circulo.i

# target to preprocess a source file
circulo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/circulo.cpp.i
.PHONY : circulo.cpp.i

circulo.s: circulo.cpp.s
.PHONY : circulo.s

# target to generate assembly for a file
circulo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/circulo.cpp.s
.PHONY : circulo.cpp.s

cubo.o: cubo.cpp.o
.PHONY : cubo.o

# target to build an object file
cubo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/cubo.cpp.o
.PHONY : cubo.cpp.o

cubo.i: cubo.cpp.i
.PHONY : cubo.i

# target to preprocess a source file
cubo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/cubo.cpp.i
.PHONY : cubo.cpp.i

cubo.s: cubo.cpp.s
.PHONY : cubo.s

# target to generate assembly for a file
cubo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/cubo.cpp.s
.PHONY : cubo.cpp.s

esfera.o: esfera.cpp.o
.PHONY : esfera.o

# target to build an object file
esfera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/esfera.cpp.o
.PHONY : esfera.cpp.o

esfera.i: esfera.cpp.i
.PHONY : esfera.i

# target to preprocess a source file
esfera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/esfera.cpp.i
.PHONY : esfera.cpp.i

esfera.s: esfera.cpp.s
.PHONY : esfera.s

# target to generate assembly for a file
esfera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/esfera.cpp.s
.PHONY : esfera.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/main.cpp.s
.PHONY : main.cpp.s

paralelepipedo.o: paralelepipedo.cpp.o
.PHONY : paralelepipedo.o

# target to build an object file
paralelepipedo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/paralelepipedo.cpp.o
.PHONY : paralelepipedo.cpp.o

paralelepipedo.i: paralelepipedo.cpp.i
.PHONY : paralelepipedo.i

# target to preprocess a source file
paralelepipedo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/paralelepipedo.cpp.i
.PHONY : paralelepipedo.cpp.i

paralelepipedo.s: paralelepipedo.cpp.s
.PHONY : paralelepipedo.s

# target to generate assembly for a file
paralelepipedo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/paralelepipedo.cpp.s
.PHONY : paralelepipedo.cpp.s

piramide.o: piramide.cpp.o
.PHONY : piramide.o

# target to build an object file
piramide.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/piramide.cpp.o
.PHONY : piramide.cpp.o

piramide.i: piramide.cpp.i
.PHONY : piramide.i

# target to preprocess a source file
piramide.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/piramide.cpp.i
.PHONY : piramide.cpp.i

piramide.s: piramide.cpp.s
.PHONY : piramide.s

# target to generate assembly for a file
piramide.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/piramide.cpp.s
.PHONY : piramide.cpp.s

quadrado.o: quadrado.cpp.o
.PHONY : quadrado.o

# target to build an object file
quadrado.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/quadrado.cpp.o
.PHONY : quadrado.cpp.o

quadrado.i: quadrado.cpp.i
.PHONY : quadrado.i

# target to preprocess a source file
quadrado.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/quadrado.cpp.i
.PHONY : quadrado.cpp.i

quadrado.s: quadrado.cpp.s
.PHONY : quadrado.s

# target to generate assembly for a file
quadrado.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/quadrado.cpp.s
.PHONY : quadrado.cpp.s

retangulo.o: retangulo.cpp.o
.PHONY : retangulo.o

# target to build an object file
retangulo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/retangulo.cpp.o
.PHONY : retangulo.cpp.o

retangulo.i: retangulo.cpp.i
.PHONY : retangulo.i

# target to preprocess a source file
retangulo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/retangulo.cpp.i
.PHONY : retangulo.cpp.i

retangulo.s: retangulo.cpp.s
.PHONY : retangulo.s

# target to generate assembly for a file
retangulo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/retangulo.cpp.s
.PHONY : retangulo.cpp.s

triangulo.o: triangulo.cpp.o
.PHONY : triangulo.o

# target to build an object file
triangulo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/triangulo.cpp.o
.PHONY : triangulo.cpp.o

triangulo.i: triangulo.cpp.i
.PHONY : triangulo.i

# target to preprocess a source file
triangulo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/triangulo.cpp.i
.PHONY : triangulo.cpp.i

triangulo.s: triangulo.cpp.s
.PHONY : triangulo.s

# target to generate assembly for a file
triangulo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GEOMETRIA.dir/build.make CMakeFiles/GEOMETRIA.dir/triangulo.cpp.s
.PHONY : triangulo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GEOMETRIA"
	@echo "... circulo.o"
	@echo "... circulo.i"
	@echo "... circulo.s"
	@echo "... cubo.o"
	@echo "... cubo.i"
	@echo "... cubo.s"
	@echo "... esfera.o"
	@echo "... esfera.i"
	@echo "... esfera.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... paralelepipedo.o"
	@echo "... paralelepipedo.i"
	@echo "... paralelepipedo.s"
	@echo "... piramide.o"
	@echo "... piramide.i"
	@echo "... piramide.s"
	@echo "... quadrado.o"
	@echo "... quadrado.i"
	@echo "... quadrado.s"
	@echo "... retangulo.o"
	@echo "... retangulo.i"
	@echo "... retangulo.s"
	@echo "... triangulo.o"
	@echo "... triangulo.i"
	@echo "... triangulo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

